name: "Build mfp"

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build-mfp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Build mfp public/index.html and public/episodes.json
        run: |
          python build-mfp.py
          bash commit-build-changes.sh
