name: "Fetch Episodes and Build mfp-app"

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build-mfp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Fetching episodes and building index.html and episodes.json
        run: |
          python mfp-fetch-and-build.py
          bash github-commit-build.sh
