name: "Build index.html"

on:
  schedule:
    - cron: "* */6 * * *"
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  update-index-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build mfp index.html and episodes.json and save changes
        run: |
          python build-mfp-static.py
          bash commit-changes.sh
